"""
Phase 3 — Manuscript writer.
Reads experiment results + figures, generates a structured cardiology manuscript
(STROBE-compliant for observational cohort studies).
"""

import os, sys, json, glob

WORK_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, WORK_DIR)
from claude_client import claude_call

SECTION_PROMPTS = {
    "abstract": """
Write a structured abstract (Background, Methods, Results, Conclusions) for a
cardiology outcomes paper. Keep it under 300 words. Use the data below.
{context}
""",

    "introduction": """
Write a 3-paragraph Introduction for a cardiology paper:
1. Burden and context of PCI outcomes (cite generic knowledge — DO NOT fabricate citations)
2. Gap in the literature that this study addresses
3. Aim of the study

Study: {title}
Hypothesis: {hypothesis}
""",

    "methods": """
Write a Methods section for a retrospective cohort study from a PCI registry.
Use STROBE reporting guidelines. Cover:
- Study design and setting (Chinese tertiary centre, 2005-2025)
- Participants (inclusion: underwent PCI; exclusion: missing endpoint data)
- Variables: {predictors}
- Statistical analysis: {method}
- Software: Python (lifelines, statsmodels, pandas), R (haven)
- Ethics: registry data with institutional approval

Keep it concise and precise. Do not invent numbers.
""",

    "results": """
Write a Results section based on the following statistical outputs.
Structure as:
1. Baseline characteristics (note key variables and their distributions)
2. Primary outcome (event rates, follow-up time)
3. Multivariable analysis results (interpret HRs, CIs, p-values exactly as given)
4. Subgroup / sensitivity findings

RESULTS DATA:
{results}

Figures available: {figures}
Reference figures as "Figure 1", "Figure 2", etc. in order.
Do not fabricate numbers — use only what appears in RESULTS DATA.
""",

    "discussion": """
Write a Discussion section (4 paragraphs):
1. Summary of main findings
2. Comparison with prior literature (reference known cardiology facts — no fabricated citations)
3. Mechanisms explaining the findings
4. Limitations (retrospective design, single-centre, potential confounding,
   missing data, SPSS dataset with varying completeness across follow-up windows)
5. Conclusions (1 sentence)

Main finding: {main_finding}
""",
}


def collect_results(search_summary: dict) -> tuple[str, list[str]]:
    results_text = ""
    figure_paths = []

    for stage, node_dict in search_summary.get("best_nodes", {}).items():
        node_dir = node_dict.get("node_dir", "")

        results_file = os.path.join(node_dir, "results.txt")
        if os.path.exists(results_file):
            with open(results_file, encoding="utf-8") as f:
                results_text += f"\n--- Stage {stage} results ---\n" + f.read()

        metrics_file = os.path.join(node_dir, "metrics.json")
        if os.path.exists(metrics_file):
            with open(metrics_file) as f:
                results_text += f"\nMetrics: {f.read()}\n"

        figs = glob.glob(os.path.join(node_dir, "figures", "*.png"))
        figure_paths.extend(figs)

    return results_text, figure_paths


def generate_manuscript(search_summary: dict) -> str:
    idea    = search_summary["idea"]
    results, figures = collect_results(search_summary)

    print("[Phase 3] Generating manuscript sections...")

    sections = {}

    sections["methods"] = claude_call(SECTION_PROMPTS["methods"].format(
        predictors=", ".join(idea.get("key_predictors", [])),
        method=idea.get("statistical_method", "Cox PH"),
    ), max_tokens=2048)

    sections["results"] = claude_call(SECTION_PROMPTS["results"].format(
        results=results[:6000],
        figures="\n".join(os.path.basename(f) for f in figures),
    ), max_tokens=2048)

    sections["introduction"] = claude_call(SECTION_PROMPTS["introduction"].format(
        title=idea["title"], hypothesis=idea["hypothesis"],
    ), max_tokens=1024)

    main_finding = results[:500] if results else "See results section."
    sections["discussion"] = claude_call(SECTION_PROMPTS["discussion"].format(
        main_finding=main_finding,
    ), max_tokens=2048)

    abstract_context = (
        f"Title: {idea['title']}\n"
        f"Methods summary: {sections['methods'][:500]}\n"
        f"Results summary: {sections['results'][:500]}\n"
    )
    sections["abstract"] = claude_call(SECTION_PROMPTS["abstract"].format(
        context=abstract_context,
    ), max_tokens=512)

    # Assemble full manuscript
    manuscript = f"""
# {idea['title']}

## Abstract
{sections['abstract']}

---

## Introduction
{sections['introduction']}

## Methods
{sections['methods']}

## Results
{sections['results']}

## Discussion
{sections['discussion']}

---
*Generated by PCI-AI-Scientist | Dataset: Chinese PCI Registry 2005-2025*
*Figures: {', '.join(os.path.basename(f) for f in figures) or 'None generated'}*
""".strip()

    out_dir = os.path.join(WORK_DIR, "phase3_writeup")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "manuscript.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(manuscript)

    # Copy figures
    import shutil
    fig_dir = os.path.join(out_dir, "figures")
    os.makedirs(fig_dir, exist_ok=True)
    for fig in figures:
        shutil.copy2(fig, fig_dir)

    print(f"[Phase 3] Manuscript saved to {out_path}")
    print(f"[Phase 3] {len(figures)} figures copied.")
    return manuscript
