"""
Stage 1 template: Kaplan-Meier survival analysis + univariate Cox regression.

Replace CSV, EVENT, TIME, and EXPOSURE with your dataset's column names.
This script is auto-generated by the AI Scientist pipeline for each study.
"""
import os, json, warnings, traceback
import numpy as np
import pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")

NODE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV      = "/path/to/your/dataset.csv"   # replace
EVENT    = "event_col"                    # replace: binary outcome (0/1)
TIME     = "time_col"                     # replace: days to event or censoring
EXPOSURE = "exposure_col"                 # replace: primary exposure variable

try:
    from lifelines import KaplanMeierFitter, CoxPHFitter
    from lifelines.statistics import logrank_test

    df = pd.read_csv(CSV, low_memory=False)
    for c in [EVENT, TIME, EXPOSURE]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    sdf = df[[EVENT, TIME, EXPOSURE]].dropna()
    # Fix censoring: if non-events have TIME=0, impute maximum follow-up
    # sdf.loc[(sdf[TIME] == 0) & (sdf[EVENT] == 0), TIME] = 365
    sdf[TIME] = sdf[TIME].clip(lower=0.5)

    grp1 = sdf[sdf[EXPOSURE] == 1]
    grp0 = sdf[sdf[EXPOSURE] == 0]
    lr   = logrank_test(grp0[TIME], grp1[TIME], grp0[EVENT], grp1[EVENT])

    # KM plot
    fig, ax = plt.subplots(figsize=(8, 5))
    for grp, lbl, col in [(grp0, "Unexposed", "steelblue"), (grp1, "Exposed", "tomato")]:
        km = KaplanMeierFitter()
        km.fit(grp[TIME], grp[EVENT], label=f"{lbl} (n={len(grp):,})")
        km.plot_survival_function(ax=ax, ci_show=True, color=col)
    ax.set_title("Survival by Exposure Status")
    ax.set_xlabel("Time"); ax.set_ylabel("Event-free probability")
    ax.text(0.05, 0.05, f"Log-rank p={lr.p_value:.2e}", transform=ax.transAxes, fontsize=10)
    ax.legend(fontsize=9); plt.tight_layout()
    fig.savefig(os.path.join(NODE_DIR, "figures", "km_curve.png"), dpi=150); plt.close()

    # Univariate Cox
    cph = CoxPHFitter(penalizer=0.1)
    cph.fit(sdf[[EVENT, TIME, EXPOSURE]], duration_col=TIME, event_col=EVENT)
    r = cph.summary.loc[EXPOSURE]

    metrics = {
        "n": int(len(sdf)), "events": int(sdf[EVENT].sum()),
        "n_exposed":    int((sdf[EXPOSURE] == 1).sum()),
        "n_unexposed":  int((sdf[EXPOSURE] == 0).sum()),
        "logrank_p":    round(float(lr.p_value), 6),
        "hr":           round(float(r["exp(coef)"]), 4),
        "hr_ci_lo":     round(float(r["exp(coef) lower 95%"]), 4),
        "hr_ci_hi":     round(float(r["exp(coef) upper 95%"]), 4),
        "p_value":      round(float(r["p"]), 4),
    }
    with open(os.path.join(NODE_DIR, "metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)
    with open(os.path.join(NODE_DIR, "results.txt"), "w") as f:
        f.write(f"N={metrics['n']:,}  Events={metrics['events']:,}\n")
        f.write(f"Exposed: n={metrics['n_exposed']:,}\n")
        f.write(f"Unexposed: n={metrics['n_unexposed']:,}\n")
        f.write(f"Log-rank p={metrics['logrank_p']:.4e}\n")
        f.write(f"Univariate HR={metrics['hr']:.3f} "
                f"[{metrics['hr_ci_lo']:.3f}-{metrics['hr_ci_hi']:.3f}] "
                f"p={metrics['p_value']:.4f}\n")
    print("STATUS: SUCCESS")
except Exception:
    traceback.print_exc(); print("STATUS: FAILED")
